project:
  type: website
  output-dir: docs

website:
  title: Property Modeling
  repo-url: https://github.com/nycdepartmentoffinance
  repo-actions: [source, issue]
  favicon: "images/favicon/logo_favicon.png"
  navbar:
    background: light
    search: true
    logo: "images/favicon/logo_transparent.png"
    left:
    - text: "Home"
      href: /
    - text: "Assessor Districts"
      href: /assessor_districts/
    - text: "Data Dictionary"
      href: /data_dictionary/
    - text: "Models"
      href: /models/
    tools:
      - icon: github
        href: https://github.com/nycdepartmentoffinance

  sidebar:
     style: "docked"
     search: true
     contents: auto

format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: source

