project:
  type: website
  output-dir: docs

website:
  title: Property Modeling
  repo-url: https://github.com/nycdepartmentoffinance/nycdepartmentoffinance.github.io
  repo-actions: [source, issue]
  favicon: "images/favicon/logo_favicon.png"
  navbar:
    background: light
    search: true
    logo: "images/favicon/logo_transparent.png"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Data Dictionary"
        href: data_dictionary.qmd
    tools:
      - icon: github
        href: https://github.com/nycdepartmentoffinance/nycdepartmentoffinance.github.io

  sidebar:
     style: "docked"
     search: true
     contents:
     - section: "Data Dictionary"
       href: data_dictionary.qmd
       contents:
        - fdw_crosswalk.qmd
        - production_columns.qmd
        - pts_columns.qmd
        - all_tables.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: source

